/**
 * PhotoCull Pro - DOM Element Mapping
 */

export const elements = {
    pages: document.querySelectorAll('.page'),
    btnBack: document.getElementById('btn-back'),
    stepTitle: document.getElementById('step-title'),
    fileInput: document.getElementById('file-input'),
    folderInput: document.getElementById('folder-input'),
    viewImg: document.getElementById('view-img'),
    fileInfo: document.getElementById('view-filename'),
    exifInfo: document.getElementById('view-exif'),
    pillContainer: document.getElementById('rating-container'),
    gridView: document.getElementById('grid-view'),
    filterStatus: document.getElementById('filter-status'),
    folderNameInput: document.getElementById('folder-name'),
    exportMethod: document.getElementById('export-method'),
    qualityNum: document.getElementById('quality-num'),
    methodHint: document.getElementById('method-hint'),
    selectedPath: document.getElementById('selected-path'),
    mainExportBtn: document.getElementById('main-export-btn'),
    btnBrowse: document.getElementById('btn-browse'),
    resChoice: document.getElementById('res-choice'),
    renamePattern: document.getElementById('rename-pattern'),
    renamePreview: document.getElementById('rename-preview'),
    renderProgress: document.getElementById('render-progress'),
    importStatus: document.getElementById('import-status'),
    exportStatsText: document.getElementById('export-stats-text'),
    exportStatusText: document.getElementById('export-status-text'),
    compareBtn: document.getElementById('btn-compare'),
    viewportContainer: document.getElementById('viewport-container'),
    compareImg: document.getElementById('compare-img'),
    shortcutsModal: document.getElementById('shortcuts-modal'),
    histogramCanvas: document.getElementById('histogram-canvas'),
    exifExtended: document.getElementById('view-exif-extended'),
    ratingPop: document.getElementById('rating-pop'),
    cullingRatingDisplay: document.getElementById('culling-rating-display'),
    btnAutoAdvance: document.getElementById('btn-autoadvance'),
    sideDrawer: document.getElementById('side-drawer'),
    drawerOverlay: document.getElementById('drawer-overlay'),
    statProgress: document.getElementById('stat-progress'),
    statRated: document.getElementById('stat-rated'),
    btnMenu: document.getElementById('btn-menu'),
    btnSort: document.getElementById('btn-sort'),
    captionInput: document.getElementById('caption-input'),
    globalByline: document.getElementById('global-byline'),
    includeSidecar: document.getElementById('include-sidecar'),
    embedMetadata: document.getElementById('embed-metadata'),
    btnLoupe: document.getElementById('btn-loupe'),
    selectionBar: document.getElementById('selection-bar'),
};
